#!/bin/bash

# imports:
##########
source ./scripts/db_table
source ./scripts/menu

########################################################################################

dbs_path="$(pwd)/DBs/"
[[ ! -e "$dbs_path" ]] && mkdir "$dbs_path"

db_menu
