#!/bin/bash
########################################################################################
# imports:
##########
source "$(dirname "$0")"/scripts/auth
source "$(dirname "$0")"/scripts/menu
source "$(dirname "$0")"/scripts/db_table
source "$(dirname "$0")"/scripts/crud
source "$(dirname "$0")"/scripts/validation
source "$(dirname "$0")"/scripts/utils

########################################################################################

# Initialize Parent Directory
dbs_path="$(dirname "$0")/.DBs"
[[ ! -e "$dbs_path" ]] && mkdir "$dbs_path"

# Initialize Credentials Directory
auth_path="$(dirname "$0")/.Credentials"
[[ ! -e "$auth_path" ]] && mkdir "$auth_path"

user="Guest"
while true; do
    auth_menu
    db_menu
done
