#!/bin/bash
########################################################################################

# helper functions:
###################

# $1: Metadata temp file
# $2: unique, notnull
restriction() {
    clear
    awk -F ":" '{print $2}' "$1" | nl -w 1 -s ") "
    counter="$colNum"
    while [[ $counter -gt 0 ]]; do
        echo
        clear_buffer
        read -r -p "Enter the column number for the $2 key, or 0 to finish: " key

        if is_int "$key"; then
            [[ $key -eq 0 ]] && break
            if [[ $key -gt 0 ]] && [[ $key -le $colNum ]]; then
                if [[ $key -eq $pk ]]; then
                    echo "'$pk_name' is already $2 as it is the primary key."
                elif $(awk -v key="$key" -v condition="$2" -F ":" 'NR==key {if ($4==condition || $5==condition) exit 0; exit 1}' "$1"); then
                    key_name=$(awk -v key="$key" -F ":" 'NR==key {print $2}' "$1")
                    echo "'$key_name' is already $2."
                else
                    sed -i "${key}s/$/:$2/" "$1"
                    ((counter--))
                fi
                continue
            fi
        fi
        echo "Invalid input. Please enter a valid column number between 1 and $colNum, or 0 to finish."
    done
}

# $1: Metadata temp file
key_init() {
    rm -f "$1"
    for ((i = 0; i < $colNum; i++)); do
        line="key"
        echo

        clear_buffer
        read -r -p "Please enter column $(($i + 1)) Name: " colName && colName=$(trim_tolower "$colName")
        [[ -z "$colName" ]] && {
            echo "Column name cannot be whitespace"
            ((i--))
            continue
        }
        line+=":$colName"

        clear_buffer
        read -r -p "Please enter column $(($i + 1)) Data Type (int/str/email/phone): " colType && colType=$(trim_tolower "$colType")
        [[ -z "$colType" ]] && {
            echo "Data Type cannot be whitespace"
            ((i--))
            continue
        }
        is_type "$colType" && line+=":$colType" || {
            echo "Data Type must be 'int' or 'str'"
            ((i--))
            continue
        }

        echo "$line" >>"$1"
    done
}

# $1: Metadata file
get_headers() {
    awk -F ':' '/^key:/ {print $2}' "$1" | paste -s -d ":" -
}

# $1: Metadata File
# $2: flag='noID'
columns_menu() {
    local meta_file="$1"
    headers=$(get_headers "$meta_file")
    num_cols=$(echo "$headers" | tr ':' '\n' | wc -l)

    echo "Select a column:"
    if [[ $2 != 'noID' ]]; then
        echo "$headers" | tr ':' '\n' | nl -w 1 -s ") "
    else
        echo "$headers" | cut -d ':' -f2- | tr ':' '\n' | nl -w 1 -s ") "
        ((num_cols--))
    fi

    echo
    clear_buffer
    read -r -p "Enter column number: " col_choice

    if ! is_int "$col_choice" || [[ $col_choice -lt 1 || $col_choice -gt $num_cols ]]; then
        col_choice=''
        col_name=''
        echo "Invalid choice!"
        return 1
    fi

    [[ $2 == 'noID' ]] && ((col_choice++))
    col_name=$(echo "$headers" | cut -d ':' -f$((col_choice)))
    return 0
}

validate_input() {
    local field="$1"
    local type="$2"
    local constraints="$3"
    local msg="$4"

    # Find column index from the header of the table file
    col_index=$(awk -F ":" -v field="$field" '
        NR==1 {
            for (i=1; i<=NF; i++) {
                if ($i == field) {
                    print i;
                    exit;
                }
            }
        }' "$table_file")

    if [[ -z "$col_index" ]]; then
        echo "❌ Error: Column '$field' not found in the table."
        return 1
    fi

    while :; do
        echo
        clear_buffer
        read -r -p "$msg" value && value=$(trim_tolower "$value")
        [[ "$value" == "N/A" ]] && value=""

        # Check PK constraint (must be unique and not null)
        [[ "$constraints" == *"pk"* ]] && {
            [[ -z "$value" ]] && echo "Error: '$field' (Primary Key) cannot be empty!" && continue
            if [[ "$constraints" == *"unique"* ]]; then
                if awk -F ":" -v col="$col_index" -v val="$value" 'NR > 1 && $col == val {exit 1}' "$table_file"; then
                    echo "Error: '$field' (Primary Key) must be unique!"
                    continue
                fi
            fi
        }

        # Check NOT NULL constraint
        [[ "$constraints" == *"notnull"* && -z "$value" ]] && echo "Error: '$field' cannot be empty." && continue

        # Check UNIQUE constraint (if not a PK)
        if [[ "$constraints" == *"unique"* ]]; then
            if ! awk -F ":" -v col="$col_index" -v val="$value" '
                NR > 1 {
                    if ($col == val) {
                        exit 1;
                    }
                }' "$table_file"; then
                echo "Error: This '$field' already exists. Please enter a different value."
                continue

            fi
        fi

        if [[ -n "$value" ]]; then
            case "$type" in
            "str")
                if ! is_str "$value"; then
                    echo "Error: '$field' must start with letter."
                    continue
                fi
                ;;
            "int")
                if ! is_int "$value"; then
                    echo "Error: '$field' must be an integer."
                    continue
                fi
                ;;
            "email")
                if ! is_email "$value"; then
                    echo "Error: Invalid email format you must enter in this format: 'john@example.com'"
                    continue
                fi
                ;;
            "phone")
                if ! is_phone "$value"; then
                    echo "Error: Invalid phone format. Must be egyption number 'ex: 010-xxx-xxx-xx' digits."
                    continue
                fi
                ;;
            *)
                echo "Error: Unknown type '$type' for '$field'."
                continue
                ;;
            esac
        fi

        # Assign reply value
        [[ -n "$value" ]] && reply="$value" || reply="N/A"
        return 0
    done
}

########################################################################################

# $1: Database Path
# $2: Table to be created
table_init() {
    clear
    while true; do
        clear_buffer
        read -r -p "Please enter number of columns: " colNum
        [[ -z "$colNum" ]] && {
            echo -e "Number of columns cannot be whitespace\n"
            continue
        }
        is_int "$colNum" && [[ $colNum -gt 0 ]] && break
        echo -e "Number of columns must be a positive integer\n"
    done

    key_init "$1/.$2.temp"
    clear
    awk -F ":" '{print $2}' "$1/.$2.temp" | nl -w 1 -s ") "
    while true; do
        echo
        clear_buffer
        read -r -p "Enter the column number for the primary key, or 0 for auto-generated ID: " pk
        is_int "$pk" && [[ $key -ge 0 ]] && [[ $key -le $colNum ]] && break
        echo "Invalid input. Please enter a valid column number between 1 and $colNum, or 0 for auto-generated ID."
    done

    [[ $pk -eq 0 ]] && pk_name="ID" || pk_name=$(awk -v pk="$pk" -F ":" 'NR==pk {print $2}' "$1/.$2.temp")
    if [[ $colNum -ne 1 ]] || [[ $pk -eq 0 ]]; then
        restriction "$1/.$2.temp" "unique"
        restriction "$1/.$2.temp" "notnull"
    fi
    [[ $pk -eq 0 ]] && {
        sed -i "1s/^/key:ID:auto\n/" "$1/.$2.temp"
        ((colNum++))
    } || sed -i "${pk}s/$/:pk/" "$1/.$2.temp"

    clear
    echo -e "Table info:\n"
    # friendlier format
    cat "$1/.$2.temp"
    echo
    clear_buffer
    read -r -n 1 -p "Press [y/Y] to confirm initialization and any other key to cancel: " confirm
    [[ $confirm != [yY] ]] && {
        echo -e "\ninitialization canceled"
        sleep 2
        return 1
    }

    echo "updated_at:$(date)" >>"$1/.$2"
    echo "columns:$colNum" >>"$1/.$2"
    echo "rows:0" >>"$1/.$2"
    echo "pk:$pk_name:$pk" >>"$1/.$2"
    cat "$1/.$2.temp" >>"$1/.$2"
    rm "$1/.$2.temp"

    get_headers "$1/.$2" >"$table_file"
    echo -e "\nTable initialized succussfully"
    sleep 2
    crud_menu "$1/.$2" "$1/$2"
}

# $1: Table Metadata File
# $2: Table Data File
crud_menu() {
    rows_md=$(awk '/^rows/ {print NR}' "$1")
    pk_md=$(awk '/^pk/ {print NR}' "$1")
    updated_at_md=$(awk '/^updated_at/ {print NR}' "$1")
    col_name=''

    while true; do
        clear
        echo "Select what you want to do in '$(basename $2)' table :"
        echo "1) Insert Record"
        echo "2) Delete Record"
        echo "3) Update Record"
        echo "4) Select Record"
        echo "5) Show All Records"
        echo "6) Exit"

        clear_buffer
        read -r -s -n 1 choice

        case "$choice" in
        1)
            insert_record "$1" "$2"
            sleep 2
            ;;
        2)
            delete_record "$1" "$2"
            sleep 2
            ;;
        3)
            update_record "$1" "$2"
            sleep 2
            ;;
        4)
            find_record "$2" "$1"
            clear_buffer
            read -r -s -n 1 -p "Press any key to continue..."
            ;;
        5)
            show_all_records "$2"
            clear_buffer
            read -r -s -n 1 -p "Press any key to continue..."
            ;;
        6) return 0 ;;
        *)
            echo "Invalid choice, please try again."
            sleep 2
            ;;
        esac

    done
}

insert_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record insertion wizard!"
    echo "*****************************************"

    declare -A field rules
    column_order=()
    clear_buffer
    while IFS=: read -r key name type constraints; do
        if [[ "$key" == "key" ]]; then
            field["$name"]="$type"
            rules["$name"]="$constraints"
            column_order+=("$name")
        fi
    done < <(grep '^key:' "$meta_file")

    new_row=""

    [[ "${field["ID"]}" == "auto" ]] && attributes=("${column_order[@]:1}") || attributes=("${column_order[@]}")

    for attr in "${attributes[@]}"; do
        type="${field[$attr]}"
        constraints="${rules[$attr]}"
        [[ "$constraints" =~ notnull ]] && msg="Enter $attr value (cannot be empty): " || msg="Enter $attr value (press enter for empty value): "
        validate_input "$attr" "$type" "$constraints" "$msg"
        new_row+="$reply:"
    done

    last_id=$(awk -F':' -v pk_md=$pk_md 'NR==pk_md {print $NF}' "$meta_file")
    new_row="$((++last_id)):${new_row}"
    echo "$new_row" >>"$table_file"

    #  increment the last_id i  meta data file
    if [[ "${field["ID"]}" == "auto" ]]; then
        sed -i "${pk_md}s/^pk:ID:[0-9]*/pk:ID:$last_id/" "$meta_file"
    fi
    row_num=$(awk -F ":" -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1")
    sed -i "${rows_md}s/rows:[0-9]*/rows:$((++row_num))/" "$meta_file"
    sed -i "${updated_at_md}s/updated_at:.*/updated_at:$(date)/" "$meta_file"

    echo -e "\nRow inserted successfully!"
}

delete_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record deletion wizard!"
    echo "*****************************************"

    find_record "$table_file" "$meta_file"
    [[ $? -ne 0 ]] && return 1

    echo "*****************************************"
    clear_buffer
    read -r -n 1 -p "Are you sure you want to delete $matching_count record(s)? (y/Y) " confirmation
    [[ "$confirmation" != [Yy] ]] && {
        echo -e "\nDeletion cancelled."
        return 1
    }

    awk -F ':' -v idx="$key_index" -v val="$value" '
    BEGIN { OFS = ":" }
    $idx != val { print }
    ' "$table_file" >temp_file && mv temp_file "$table_file"

    row_num=$(($(awk -F ":" -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1") - $matching_count))
    sed -i "${rows_md}s/rows:[0-9]*/rows:$row_num/" "$meta_file"
    sed -i "${updated_at_md}s/updated_at:.*/updated_at:$(date)/" "$meta_file"

    echo -e "\nRecord(s) deleted successfully!"
}

# $1: Table Data File
# $2: Meta Data File
find_record() {
    local table_file="$1"
    local meta_file="$2"

    clear
    echo "Welcome to the Find wizard!"
    echo "*****************************************"

    clear_buffer
    columns_menu "$meta_file"
    [[ $? -ne 0 ]] && return 1

    key=$col_name
    key_index=$(awk -F ':' -v key="$key" 'NR==1 {for (i=1; i<=NF; i++) if ($i == key) print i}' "$table_file")
    [[ -z "$key_index" ]] && {
        echo -e "\nError: Column '$key' not found."
        return 1
    }

    clear_buffer
    read -r -p "Enter the value: " value && value=$(trim_tolower "$value")
    [[ -z "$value" || "$value" =~ ^(n/a|na)$ ]] && value="N/A"

    # Make `matching_rec` and `matching_count` global
    escaped_value=$(echo "$value" | sed 's/[\/&]/\\&/g')
    matching_rec=$(sed -n "/^\([^:]*:\)\{$((key_index - 1))\}$escaped_value:/p" "$table_file")
    matching_count=$([[ -n "$matching_rec" ]] && echo "$matching_rec" | wc -l || echo 0)

    [[ "$matching_count" -eq 0 ]] && {
        echo -e "\nError: No matching records found."
        return 1
    }

    clear
    echo "Matching record(s):"
    echo "*****************************************"
    {
        sed -n '1p' "$table_file"
        echo "$matching_rec"
    } | column -t -s ':'
}

update_record() {
    local meta_file="$1"
    local table_file="$2"

    clear
    echo "Welcome to the record/s updating wizard!"
    echo "*****************************************"

    clear_buffer
    headers=$(get_headers "$meta_file")
    if [[ "$headers" =~ ^ID ]]; then
        columns_menu "$meta_file" 'noID'
    else
        columns_menu "$meta_file"
    fi

    [[ $? -eq 1 ]] && return 1
    key=$col_name

    # Find column index
    local key_index=$(awk -F ':' -v key="$key" 'NR==1 {for (i=1; i<=NF; i++) if ($i == key) print i}' "$table_file")
    [[ -z "$key_index" ]] && {
        echo -e "\nError: Column '$key' not found."
        return 1
    }

    clear_buffer
    read -r -p "Enter the value to update: " old_value && old_value=$(trim_tolower "$old_value")
    [[ -z "$old_value" || "$old_value" =~ ^(n/a|na)$ ]] && old_value="N/A"

    local matching_rec=$(awk -F ':' -v idx="$key_index" -v val="$old_value" 'NR>1 && $idx == val' "$table_file")

    local matching_count=$([[ -n "$matching_rec" ]] && echo "$matching_rec" | wc -l || echo 0)
    [[ "$matching_count" -eq 0 ]] && {
        echo -e "\nError: No matching records found."
        return 1
    }

    local field_type=$(awk -F ":" -v key="$key" '$2 == key {print $3}' "$meta_file")
    local field_constraints=$(awk -F ":" -v key="$key" '$2 == key {print $4}' "$meta_file")

    [[ $constraints =~ notnull ]] && msg="Enter $attr value (cannot be empty): " || msg="Enter $attr value (press enter for empty value): "

    validate_input "$key" "$field_type" "$field_constraints" "$msg"
    [[ $? -eq 0 ]] &&
        new_value="$reply"

    clear_buffer
    read -r -n 1 -p "Are you sure you want to update $matching_count record(s)? (y/Y) " confirmation
    [[ "$confirmation" != [Yy] ]] && {
        echo -e "\nUpdating cancelled."
        return 1
    }

    awk -F ':' -v idx="$key_index" -v old_val="$old_value" -v new_val="$new_value" '
       BEGIN { OFS = ":" }
       NR == 1 { print; next }
       {
         if ($idx == old_val) {
             $idx = new_val
         }
         print
       }
    ' "$table_file" >temp_file && mv temp_file "$table_file"

    sed -i "/^updated_at:/s/.*/updated_at: $(date)/" "$meta_file"

    echo -e "\nRecord(s) updated successfully!"
}

show_all_records() {
    local table_file="$1"
    clear
    [[ $(wc -l <"$table_file") -gt 1 ]] && column -t -s ':' "$table_file" && return 0
    echo "No records found." && return 1
}

# $1: Database Path
# $2: Table to be created
select_table() {
    [[ -s "$1/$2" ]] && crud_menu "$1/.$2" "$1/$2" || table_init "$1" "$2"
}
