#!/bin/bash
########################################################################################

# helper functions:
###################

# $1: Metadata temp file
# $2: unique, notnull
restriction() {
    clear
    awk -F ":" '{print $2}' "$1" | nl -w 1 -s ") "
    while true; do
        echo
        clear_buffer
        read -p "Enter the column number for the $2 key, or 0 to finish: " key

        if is_int "$key"; then
            [[ $key -eq 0 ]] && break
            if [[ $key -gt 0 ]] && [[ $key -le $colNum ]]; then
                if [[ $key -eq $pk ]]; then
                    echo "'$pk_name' is already $2 as it is the primary key."
                elif $(awk -v key="$key" -v condition="$2" -F ":" 'NR==key {if ($4==condition || $5==condition) exit 0; exit 1}' "$1"); then
                    key_name=$(awk -v key="$key" -F ":" 'NR==key {print $2}' "$1")
                    echo "'$key_name' is already $2."
                else
                    sed -i "${key}s/$/:$2/" "$1"
                fi
                continue
            fi
        fi
        echo "Invalid input. Please enter a valid column number between 1 and $colNum, or 0 to finish."
    done
}

# $1: Metadata temp file
key_init() {
    rm -f "$1"
    for ((i = 0; i < $colNum; i++)); do
        line="key"
        echo

        clear_buffer
        read -p "Please enter column $(($i + 1)) Name: " colName && colName=$(trim_tolower "$colName")
        [[ -z "$colName" ]] && {
            echo "Column name cannot be whitespace"
            ((i--))
            continue
        }
        line+=":$colName"

        clear_buffer
        read -p "Please enter column $(($i + 1)) Data Type (int/str/email/phone): " colType && colType=$(trim_tolower "$colType")
        [[ -z "$colType" ]] && {
            echo "Data Type cannot be whitespace"
            ((i--))
            continue
        }
        is_type "$colType" && line+=":$colType" || {
            echo "Data Type must be 'int' or 'str'"
            ((i--))
            continue
        }

        echo "$line" >>"$1"
    done
}

# $1: Table meta-data File
# $2: Table Data File
write_headers() {
    local meta_file="$1"
    local table_file="$2"

    # Generate headers
    header=$(awk -F ':' '/^key:/ {print $2}' "$meta_file" | paste -sd ":" -)

    # Write headers to the DB file
    echo "$header" >"$table_file"
}

########################################################################################

# $1: Database Path
# $2: Table to be created
table_init() {
    clear
    while true; do
        clear_buffer
        read -p "Please enter number of columns: " colNum
        [[ -z "$colNum" ]] && {
            echo -e "Number of columns cannot be whitespace\n"
            continue
        }
        is_int "$colNum" && [[ $colNum -gt 0 ]] && break
        echo -e "Number of columns must be a positive integer\n"
    done

    key_init "$1/.$2.temp"
    clear
    awk -F ":" '{print $2}' "$1/.$2.temp" | nl -w 1 -s ") "
    while true; do
        echo
        clear_buffer
        read -p "Enter the column number for the primary key, or 0 for auto-generated ID: " pk
        is_int "$pk" && [[ $key -ge 0 ]] && [[ $key -le $colNum ]] && break
        echo "Invalid input. Please enter a valid column number between 1 and $colNum, or 0 for auto-generated ID."
    done

    [[ $pk -eq 0 ]] && pk_name="ID" || pk_name=$(awk -v pk="$pk" -F ":" 'NR==pk {print $2}' "$1/.$2.temp")
    if [[ $colNum -ne 1 ]] || [[ $pk -eq 0 ]]; then
        restriction "$1/.$2.temp" "unique"
        restriction "$1/.$2.temp" "notnull"
    fi
    [[ $pk -eq 0 ]] && {
        sed -i "1s/^/key:ID:auto\n/" "$1/.$2.temp"
        ((colNum++))
    } || sed -i "${pk}s/$/:pk/" "$1/.$2.temp"

    clear
    echo -e "Table info:\n"
    # friendlier format
    cat "$1/.$2.temp"
    echo
    clear_buffer
    read -s -n 1 -p "Press [y/Y] to confirm initialization and any other key to cancel: " confirm
    [[ $confirm != [yY] ]] && {
        echo -e "\ninitialization canceled"
        sleep 2
        return 1
    }

    echo "db_name:$(basename "$1")" >>"$1/.$2"
    echo "table_name:$2" >>"$1/.$2"
    echo "created_at:$(date)" >>"$1/.$2"
    echo "updated_at:$(date)" >>"$1/.$2"
    echo "columns:$colNum" >>"$1/.$2"
    echo "rows:0" >>"$1/.$2"
    echo "pk:$pk_name:$pk" >>"$1/.$2"
    cat "$1/.$2.temp" >>"$1/.$2"
    rm "$1/.$2.temp"

    write_headers "$1/.$2" "$1/$2"

    echo -e "\nTable initialized succussfully"
    sleep 2
    crud_menu "$1/.$2" "$1/$2"
}

# $1: Table Metadata File
# $2: Table Data File
crud_menu() {
    rows_md=$(awk -F ":" '/^rows:/ {print NR}' "$1")
    row_num=$(awk -F':' -v rows_md="$rows_md" 'NR==rows_md {print $NF}' "$1")
    pk_md=$(awk -F ":" '/^pk:/ {print NR}' "$1")
    updated_at_md=$(awk -F ":" '/^updated_at:/ {print NR}' "$1")

    while true; do
        clear
        echo "Select what you want to do in table :"
        echo "1) Insert Record"
        echo "2) Delete Record"
        echo "3) Update Record"
        echo "4) Find Record"
        echo "5) Show All Records"
        echo "6) Exit"

        clear_buffer
        read -s -n 1 choice

        case "$choice" in
        1) insert_record "$1" "$2" ;;
        2) delete_record ;;
        3) update_record ;;
        4) find_record ;;
        5)
            show_all_records "$2"
            clear_buffer
            read -s -n 1 -p "Press any key to continue..."
            ;;
        6) break ;;
        *)
            echo "Invalid choice, please try again."
            sleep 2
            ;;
        esac

    done
}

# $1: Database Path
# $2: Table to be created
select_table() {
    [[ -s "$1/.$2" ]] && crud_menu "$1/.$2" "$1/$2" || table_init "$1" "$2"
}

# $1: Table meta-data File
# $2: Table Data File
validate_input() {
    local field="$1"
    local type="$2"
    local constraints="$3"

    while :; do
        clear_buffer
        read -p "Enter $field: " value
        value=$(trim_tolower "$value")
        [[ "$value" == "N/A" ]] && value=""

        # Check PK constraint (must be unique and not null)
        [[ "$constraints" == *"pk"* ]] && {
            [[ -z "$value" ]] && echo "Error: $field (Primary Key) cannot be empty!" && continue
            grep -q "$value:" "$table_file" && echo "Error: $field (Primary Key) must be unique!" && continue
        }

        # Check NOT NULL constraint
        [[ "$constraints" == *"notnull"* && -z "$value" ]] && echo "Error: $field cannot be empty." && continue

        # Check UNIQUE constraint (if not a PK)
        [[ "$constraints" == *"unique"* && $(grep -q "$value:" "$table_file") -gt 0 ]] && echo "Error: $field must be unique." && continue

        if [[ ! -z $value ]]; then
            case "$type" in
            "str")
                if ! is_str "$value"; then
                    echo "Error: $field must start with letter."
                    continue
                fi
                ;;
            "int")
                if ! is_int "$value"; then
                    echo "Error: $field must be an integer."
                    continue
                fi
                ;;
            "email")
                if ! is_email "$value"; then
                    echo "Error: Invalid email format youm must enter in this format john@example.com"
                    continue
                fi
                ;;
            "phone")
                if ! is_phone "$value"; then
                    echo "Error: Invalid phone format. Must be 10-15 digits."
                    continue
                fi
                ;;
            *)
                echo "Error: Unknown type $type for $field."
                continue
                ;;
            esac
        fi
        [[ -n "$value" ]] && reply="$value" || reply="N\A"
        return 0
    done
}

# $1: Table meta-data File
# $2: Table Data File
insert_record() {
    clear
    echo "Welcome to the record insertion wizard!"
    echo "*****************************************"
    local meta_file="$1"
    local table_file="$2"

    declare -A field rules
    column_order=()

    while IFS=: read -r key name type constraints; do
        if [[ "$key" == "key" ]]; then
            field["$name"]="$type"
            rules["$name"]="$constraints"
            column_order+=("$name")
        fi
    done < <(grep '^key:' "$meta_file")

    new_row=""

    if [[ "${field["ID"]}" == "auto" ]]; then
        last_id=$(awk -F':' -v pk_md=$pk_md 'NR==pk_md {print $NF}' "$meta_file")
        new_id=$((last_id + 1))
        new_row="$new_id:"
        attributes=("${column_order[@]:1}")
    else
        attributes=("${column_order[@]}")
    fi

    for attr in "${attributes[@]}"; do
        type="${field[$attr]}"
        constraints="${rules[$attr]}"
        while :; do
            validate_input "$attr" "$type" "$constraints"
            if [[ $? -eq 0 ]]; then
                new_row+="$reply:"
                break
            fi
        done
    done

    echo "$new_row" >>"$table_file"

    #  increment the last_id i  meta data file
    if [[ "${field["ID"]}" == "auto" ]]; then
        sed -i "${pk_md}s/^pk:ID:[0-9]*/pk:ID:$new_id/" "$meta_file"
    fi

    sed -i "${rows_md}s/rows:[0-9]*/rows:$(($row_num + 1))/" "$meta_file"
    sed -i "${updated_at_md}s/updated_at:.*/updated_at:$(date)/" "$meta_file"

    echo "Row inserted successfully!"
}

# $1: Table Data File
show_all_records() {
    local table_file="$1"
    clear
    column -t -s ':' "$table_file"
}
