#!/bin/bash

########################################################################################

# helper functions:
###################

# $1: Database
is_empty() {
	for item in "$1"/*
	do
		if [[ -s "$item" ]]
		then
			return 1
		fi
	done
	return 0
}

########################################################################################

# main functions:
#################

# $1: Database or Table to be created
# $2: 'db': Database, 'table': Table
create() {
	name=$(basename $1)
	
	if [[ -e "$1" ]]
	then
		echo "$name already exists."
		return 1
	fi

	if [[ $2 == 'db' ]]
	then
		mkdir "$1"
	elif [[ $2 == 'table' ]]
	then
		touch "$1"
	else
        echo "Invalid Type."
		return 1
	fi
	
	echo "'$name' created successfully."
	return 0
}

# $1: Database or Table to be deleted
# $2: 'db': Database, 'table': Table
delete() {
	name=$(basename $1)
	del='y'
	
    if [[ ! -e "$1" ]]
    then
        echo "'$name' does not exist."
        return 1
    fi

    if [[ $2 == "db" ]]
    then
        if ! is_empty "$1"
        then
            echo "The Database is not empty, are you sure you want to delete it?"
            read -n 1 -p"press [y/Y] to confirm delete and any other key to cancel: " del
            echo
        fi
    elif [[ $2 == "table" ]]
    then
        if [[ -s "$1" ]]
        then
            echo "The Table is not empty, are you sure you want to delete it?"
            read -n 1 -p"press [y/Y] to confirm delete and any other key to cancel: " del
            echo
        fi
    else
        echo "Invalid Type."
        return 1
    fi
    
    if [[ $del == [yY] ]]
    then
		rm -r "$1"
		echo "'$name' is deleted successfully."
		return 0
	else
		echo "delete canceled"
		return 1
	fi
}


# $1: parent directory
# $2: old name
rename(){
	read -p "Please enter the new name: " new_name
	if [[ -e "$1"/"$new_name" ]]
	then
		echo "$new_name already exists"
		return 1
	fi
	
	mv "$1/$2" "$1/$new_name"
	echo "'$2' is renamed successfully to '$new_name'"
	return 0
}


########################################################################################

# exports:
##########
export -f create
export -f delete
export -f rename
