#!/usr/bin/bash
########################################################################################

db_menu() {
    while true; do
        clear
        echo "Welcome $user to our DBMS, select what you want to do:"
        echo "1) Create Database."
        echo "2) Select Database."
        echo "3) Rename Database."
        echo "4) Delete Database."
        echo "5) View Databases."
        echo "6) Logout."
        echo "7) Exit BDMS."

        clear_buffer
        read -r -s -n 1 option
        clear

        case $option in
        1)
            clear_buffer
            read -r -p "Please enter the name of the Database you want to create: " db_name && db_name=$(trim_tolower "$db_name")
            create "$dbs_path" "$db_name" "db"
            sleep 2
            ;;
        2)
            clear_buffer
            read -r -p "Please enter the name of the Database you want to select: " db_name && db_name=$(trim_tolower "$db_name")
            [[ -z "$db_name" ]] && {
                echo "Name cannot be whitespace"
                sleep 2
                continue
            }
            ! is_str "$db_name" && {
                echo "Invalid name. The name must start with a letter and cannot contain ':' or '/'."
                sleep 2
                continue
            }
            [[ ! -e "$dbs_path/$db_name" ]] && {
                echo "'$db_name' does not exist."
                sleep 2
            } || table_menu "$db_name"
            ;;
        3)
            clear_buffer
            read -r -p "Please enter the name of the Database you want to rename: " db_name && db_name=$(trim_tolower "$db_name")
            [[ -z "$db_name" ]] && {
                echo "Name cannot be whitespace"
                sleep 2
                continue
            }
            ! is_str "$db_name" && {
                echo "Invalid name. The name must start with a letter and cannot contain ':' or '/'."
                sleep 2
                continue
            }
            [[ ! -e "$dbs_path/$db_name" ]] && echo "'$db_name' does not exist." || rename "$db_name" "db"
            sleep 2
            ;;
        4)
            clear_buffer
            read -r -p "Please enter the name of the Database you want to delete: " db_name && db_name=$(trim_tolower "$db_name")
            delete "$dbs_path" "$db_name" "db"
            sleep 2
            ;;
        5)
            content=$(ls "$dbs_path")
            [[ -z "$content" ]] && echo -e "No Databases exist\n" || {
                echo "Databases:"
                echo -e "\n$content\n"
            }
            clear_buffer
            read -r -s -n 1 -p "Press any key to continue..."
            ;;
        6)
            echo "Goodbye $user!"
            sleep 2
            return 0
            ;;
        7)
            echo "Goodbye $user!"
            sleep 2
            exit 0
            ;;
        *)
            echo "Invalid option. Please try again."
            sleep 2
            ;;
        esac
    done
}

table_menu() {
    db_path="$dbs_path/$1"
    while true; do
        clear
        echo "Select what you want to do in Database '"$1"':"
        echo "1) Create Table."
        echo "2) Select Table."
        echo "3) Rename Table."
        echo "4) Delete Table."
        echo "5) View Tables."
        echo "6) Return to Main Menu."

        clear_buffer
        read -r -s -n 1 option
        clear

        case $option in
        1)
            clear_buffer
            read -r -p "Please enter the name of the Table you want to create: " table_name && table_name=$(trim_tolower "$table_name")
            create "$db_path" "$table_name" "table"
            sleep 2
            ;;
        2)
            clear_buffer
            read -r -p "Please enter the name of the Table you want to select: " table_name && table_name=$(trim_tolower "$table_name")
            [[ -z "$table_name" ]] && {
                echo "Name cannot be whitespace"
                sleep 2
                continue
            }
            ! is_str "$table_name" && {
                echo "Invalid name. The name must start with a letter and cannot contain ':' or '/'."
                sleep 2
                continue
            }
            [[ ! -e "$db_path/$table_name" ]] && {
                echo "'$table_name' does not exist."
                sleep 2
            } || select_table "$db_path" "$table_name"
            ;;
        3)
            clear_buffer
            read -r -p "Please enter the name of the Table you want to rename: " table_name && table_name=$(trim_tolower "$table_name")
            [[ -z "$table_name" ]] && {
                echo "Name cannot be whitespace"
                sleep 2
                continue
            }
            ! is_str "$table_name" && {
                echo "Invalid name. The name must start with a letter and cannot contain ':' or '/'."
                sleep 2
                continue
            }
            [[ ! -e "$db_path/$table_name" ]] && echo "'$table_name' does not exist." || rename "$table_name" "table"
            sleep 2
            ;;
        4)
            clear_buffer
            read -r -p "Please enter the name of the Table you want to delete: " table_name && table_name=$(trim_tolower "$table_name")
            delete "$db_path" "$table_name" "table"
            sleep 2
            ;;
        5)
            content=$(ls "$db_path")
            [[ -z "$content" ]] && echo -e "No Tables in '$1' exist\n" || {
                echo "Tables in '$1':"
                echo -e "\n$content\n"
            }
            clear_buffer
            read -r -s -n 1 -p "Press any key to continue..."
            ;;
        6)
            return 0
            ;;
        *)
            echo "Invalid option. Please try again."
            sleep 2
            ;;
        esac
    done
}
